### ISSUE TITLE
Tree for oli?

### ISSUE THREAD

**Issue by AgustinPardo** [jtmccr1/sars2#3]
Hello,

Is this the repository of this app: https://jtmccr1.github.io/tree-for-oli/?

Regards

**Comment by jtmccr1** [comment]
This is the figure for https://artic.network/hCoV-19-viz . I'm closing the issue since I think my response in that repo covers it, but feel free to reopen if not.

**Comment by liamxg** [comment]
Dear @jtmccr1,

I hope you're doing well.

Could you kindly advise me on how to prepare my own phylogenetic tree and metadata for use with the project? I’d appreciate any guidance or best practices you can share.

Best regards,
Liam
